### ISSUE TITLE
datatable from DT 0.2.10 not rendering in Shiny

### ISSUE THREAD

**Issue by olgamie** [rstudio/DT#386]
My code:

    library(shiny)
    library(magrittr)

    ui <- shinyUI(fluidPage(
        DT::dataTableOutput("tbl")
    ))

    server <- shinyServer(function(input, output) {
      output$tbl <- DT::renderDataTable({
        DT::datatable(iris)
      })
  
    })
    shinyApp(ui = ui, server = server)

it works with:

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=pl_PL.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=pl_PL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5      shiny_0.14.2.9001

loaded via a namespace (and not attached):
 [1] htmlwidgets_0.8 R6_2.2.0        htmltools_0.3.5 tools_3.3.2     yaml_2.1.14     Rcpp_0.12.8     DT_0.2         
 [8] jsonlite_1.1    digest_0.6.10   xtable_1.8-2    httpuv_1.3.3    mime_0.5  
```

DT 0.2 is on cran currently.

But when I switch to DT 0.2.10:

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=pl_PL.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=pl_PL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5      shiny_0.14.2.9001

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8     digest_0.6.10   withr_1.0.2     mime_0.5        R6_2.2.0        xtable_1.8-2    jsonlite_1.1   
 [8] git2r_0.15.0    httr_1.2.1      curl_2.2        DT_0.2.10       devtools_1.12.0 tools_3.3.2     htmlwidgets_0.8
[15] httpuv_1.3.3    yaml_2.1.14     memoise_1.0.0   htmltools_0.3.5 knitr_1.14  
```

nothing is rendered in the app and in the developers tools console I can see:

```
Uncaught ReferenceError: crosstalk is not defined
    at Object.initialize (http://127.0.0.1:6535/datatables-binding-0.2.10/datatables.js:97:27)
    at exports.OutputBinding.shinyBinding.renderValue (http://127.0.0.1:6535/htmlwidgets-0.8/htmlwidgets.js:510:37)
    at exports.OutputBinding.onValueChange (http://127.0.0.1:6535/shared/shiny.min.js:4:172)
    at exports.OutputBinding.delegator.(anonymous function) [as onValueChange] (http://127.0.0.1:6535/htmlwidgets-0.8/htmlwidgets.js:112:23)
    at OutputBindingAdapter.onValueChange (http://127.0.0.1:6535/shared/shiny.min.js:4:19751)
    at ShinyApp.receiveOutput (http://127.0.0.1:6535/shared/shiny.min.js:3:20097)
    at ShinyApp.<anonymous> (http://127.0.0.1:6535/shared/shiny.min.js:3:22029)
    at ShinyApp._sendMessagesToHandlers (http://127.0.0.1:6535/shared/shiny.min.js:3:21834)
    at ShinyApp.dispatchMessage (http://127.0.0.1:6535/shared/shiny.min.js:3:21624)
    at WebSocket.c.onmessage (http://127.0.0.1:6535/shared/shiny.min.js:3:17488)

and 

datatables.js:985 Uncaught TypeError: Cannot read property 'data' of undefined
    at Object.resize (http://127.0.0.1:6535/datatables-binding-0.2.10/datatables.js:985:17)
    at exports.OutputBinding.shinyBinding.resize (http://127.0.0.1:6535/htmlwidgets-0.8/htmlwidgets.js:526:24)
    at http://127.0.0.1:6535/shared/shiny.min.js:4:19619
    at OutputBindingAdapter.onResize (http://127.0.0.1:6535/shared/shiny.min.js:3:1260)
    at HTMLDivElement.<anonymous> (http://127.0.0.1:6535/shared/shiny.min.js:3:7248)
    at Function.each (http://127.0.0.1:6535/shared/jquery.min.js:2:2881)
    at n.fn.init.each (http://127.0.0.1:6535/shared/jquery.min.js:2:846)
    at j (http://127.0.0.1:6535/shared/shiny.min.js:3:7117)
    at Debouncer.$invoke (http://127.0.0.1:6535/shared/shiny.min.js:3:12252)
    at http://127.0.0.1:6535/shared/shiny.min.js:3:11955
```

I'm rendering the app to chrome directly.

**Comment by XD-DENG** [comment]
Encounter the same issue. 

Received warning to install package "crosstalk" first. After installing crosstalk, the tables are rendered on Shiny page while no error or warning in console.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
